name: Android CI

on:
  push:
    branches: [ "main", "ci-cd"]
  pull_request:
    branches: [ "main", "ci-cd" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle


    - name: Create google-services
      run: touch /home/runner/work/com.google.firebaseengage/com.google.firebaseengage/app/google-services.json | base64

    - name: Populate google-services
      env:
        DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $DATA > /home/runner/work/com.google.firebaseengage/com.google.firebaseengage/app/google-services.json

    - name: Create secrets props
      run: touch /home/runner/work/com.google.firebaseengage/com.google.firebaseengage/secrets.properties | base64

    - name: Populate secrets props
      env:
        DATA: ${{ secrets.SECRET_PROPERTIES }}
      run: echo $DATA > /home/runner/work/com.google.firebaseengage/com.google.firebaseengage/secrets.properties

    - name: Decode Keystore
      env:
          ENCODED_STRING: ${{ secrets.SOKOLOVV_KEYSTORE_FILE_BASE64 }}
      run: echo $ENCODED_STRING | base64 -di > /home/runner/work/com.google.firebaseengage/com.google.firebaseengage/
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
